"""所有面向使用者的繁體中文文字集中於此。"""

# 通用訊息
GENERIC_ERROR = "操作失敗，請稍後再試。錯誤追蹤碼：`{correlation_id}`"
GUILD_ONLY = "此功能只能在伺服器內使用。"
ADMIN_ONLY = "你需要「管理伺服器」權限才能使用此功能。"
INVALID_INPUT = "輸入內容不正確：{reason}"
NOT_FOUND = "找不到指定資料，可能已結束或被移除。"
CURRENT_CHANNEL_NOT_FOUND = "找不到目前頻道。"
ACTIVITY_MESSAGE_NOT_FOUND = "找不到活動訊息。"
SUCCESS = "設定已儲存。"
CMD_SETUP_DESC = "部署或更新常駐功能儀表板"
CMD_SETTINGS_DESC = "開啟伺服器設定面板"

# 狀態徽章：面板統一用這四個符號表達「成功／未設定／需注意／失敗」，語意見 ui.status
STATUS_BADGE_OK = "✅"
STATUS_BADGE_OFF = "⬜"
STATUS_BADGE_WARN = "⚠️"
STATUS_BADGE_ERROR = "❌"

# 儀表板與設定面板文字
DASHBOARD_TITLE = "# ❄️ HoRo 儀表板"
DASHBOARD_BODY = "選擇下方功能；所有操作都會以私人訊息面板回覆。"
DASHBOARD_UPDATED = "儀表板已部署或更新。"
DASHBOARD_STALE = "這是舊版儀表板，請改用伺服器目前的儀表板。"
DASHBOARD_ECONOMY = "經濟"
DASHBOARD_GAME = "遊戲"
DASHBOARD_GIVEAWAY = "抽獎商店"
DASHBOARD_POLL = "投票"

SETTINGS_TITLE = "伺服器設定"
SETTINGS_LOG = "日誌"
SETTINGS_ECONOMY = "經濟與 21 點"
SETTINGS_POLL = "投票權限"
SETTINGS_AI = "AI 聊天"
SETTINGS_MODEL = "選擇 AI 模型"
SETTINGS_AI_QUOTA = "編輯配額"
PREVIOUS_PAGE = "上一頁"
NEXT_PAGE = "下一頁"
NAV_BACK = "返回"
PAGE_INDICATOR = "第 {page} / {total} 頁"
# settings 各頁共用的導覽選單：選項文字集中在這裡，nav.py 只負責組裝元件
NAV_SETTINGS_PLACEHOLDER = "切換設定頁"
NAV_CURRENT_MARK = "✓"
NAV_SETTINGS_HOME = "設定總覽"
NAV_SETTINGS_HOME_DESC = "一次看完四個模組目前的狀態"
NAV_LOG_DESC = "指定日誌頻道，並開關要記錄的事件"
NAV_ECONOMY_DESC = "貨幣名稱、每日簽到與 21 點下注上下限"
NAV_POLL_DESC = "指定可以建立投票的身分組"
NAV_AI_DESC = "AI 的觸發範圍、模型與每日配額"

# 各設定頁頂端的說明文字。Discord 的 subtext 語法（行首 `-# ` 的灰色小字）直接寫進常數值：
# 前綴是這段文字外觀的一部分，寫在這裡各頁就只要 `body = strings.X`，
# 不必在五個頁面模組裡各拼一次字串，也不會有人漏拼或拼成不同樣子。
SETTINGS_HOME_BODY = "-# 從下方選單切換到各模組進行設定。"
SETTINGS_LOG_BODY = "-# 選好頻道立即生效；清空選擇即停用日誌。"
SETTINGS_ECONOMY_BODY = "-# 這幾項是數字與名稱，需要用編輯視窗輸入。"
SETTINGS_POLL_BODY = "-# 留空代表只有具備「管理伺服器」權限的人能建立投票。"
SETTINGS_AI_BODY = (
    "-# AI 僅在白名單頻道中，於提及 Bot 或回覆 Bot 時觸發；頻道與身分組都要設定才會生效。"
)

SETTINGS_LOG_TOGGLES = "日誌事件開關"
SETTINGS_LOG_MEMBERS = "成員事件"
SETTINGS_LOG_MESSAGES = "訊息事件"
LOG_CHANNEL = "日誌頻道"
CURRENCY_NAME = "貨幣名稱"
DAILY_AMOUNT = "每日簽到金額"
BLACKJACK_MIN_BET = "21 點最低下注"
BLACKJACK_MAX_BET = "21 點最高下注"
POLL_ROLES = "可建立投票的身分組"
AI_CHANNELS = "白名單頻道"
AI_ROLES = "允許的身分組"
AI_MODEL = "AI 模型"
AI_GUILD_QUOTA = "伺服器每日 AI 配額"
AI_USER_QUOTA = "每位使用者每日 AI 配額"
# AI 頁摘要第三行的短版標籤：AI_GUILD_QUOTA／AI_USER_QUOTA 留給 AIQuotaModal 的欄位標籤，
# 兩者情境不同（欄位標籤要精確、摘要行要精簡），因此各自成一份常數，不共用。
AI_QUOTA_LINE = "每日配額：伺服器 **{guild}**｜每人 **{user}**"

# 各頁選擇器的提示文字（收合時顯示在空選擇器上）
LOG_CHANNEL_PLACEHOLDER = "選擇要接收日誌的頻道"
POLL_ROLES_PLACEHOLDER = "選擇可以建立投票的身分組"
AI_CHANNELS_PLACEHOLDER = "選擇 AI 可以回應的頻道"
AI_ROLES_PLACEHOLDER = "選擇可以使用 AI 的身分組"
AI_MODEL_PLACEHOLDER = "選擇要使用的模型"

# 經濟／抽獎商店／投票／21 點功能文字
ECONOMY_TITLE = "# 💎 經濟中心"
DAILY = "每日簽到"
LEADERBOARD = "排行榜"
LEADERBOARD_HEADER = "# 🏆 排行榜"
LEADERBOARD_EMPTY = "目前還沒有資料。"
TRANSFER = "轉帳"
ADMIN_ADJUST = "管理員發放／扣除"
RECIPIENT = "收款人"
RECIPIENT_PLACEHOLDER = "選擇要轉帳的對象"
TARGET_USER = "調整對象"
TARGET_USER_PLACEHOLDER = "選擇要調整餘額的對象"
AMOUNT = "金額"
REASON = "原因（選填）"
TRANSFER_MODAL_TITLE = "轉帳"
ADMIN_ADJUST_MODAL_TITLE = "管理員調整餘額"
ADMIN_ADJUST_DONE = "調整完成；<@{user_id}> 目前餘額為 **{balance}**。"
ADMIN_ADJUST_PLACEHOLDER = "可輸入負數，例如 -100"
DAILY_CLAIMED = "簽到成功！獲得 **{amount} {currency}**，目前餘額 **{balance}**。"
DAILY_ALREADY = "今天已經簽到過了，請在台北時間午夜後再來。"
BALANCE_TEXT = "你目前有 **{balance} {currency}**。"
TRANSFER_DONE = "已轉帳 **{amount} {currency}** 給 <@{user_id}>。"
INSUFFICIENT_BALANCE = "餘額不足。"
AMOUNT_POSITIVE = "金額必須是大於 0 的整數。"

GIVEAWAY_TITLE = "# 🎁 抽獎商店"
GIVEAWAY_CREATE = "建立抽獎"
GIVEAWAY_BUY = "購買抽獎券"
GIVEAWAY_LIST = "查看付費抽獎"
GIVEAWAY_JOIN_OR_BUY = "參加／購買 1 券"
GIVEAWAY_REROLL = "重抽"
GIVEAWAY_PRIZE = "獎品"
GIVEAWAY_WINNER_COUNT = "得獎名額"
GIVEAWAY_DURATION = "時長（例如 30m、2h、3d）"
GIVEAWAY_TICKET_PRICE = "每張券價格（0 代表免費）"
GIVEAWAY_PER_USER_LIMIT = "每人上限"
GIVEAWAY_ID = "抽獎編號"
GIVEAWAY_PICK_PLACEHOLDER = "選擇抽獎活動"
GIVEAWAY_NONE_ACTIVE = "目前沒有進行中的抽獎。"
GIVEAWAY_NONE_COMPLETED = "目前沒有已結束的抽獎可以重抽。"
GIVEAWAY_OPTION = "#{id}｜{prize}"
GIVEAWAY_QUANTITY = "購買張數"
GIVEAWAY_DURATION_FORMAT_ERROR = "時長格式須為數字加 m、h 或 d。"
GIVEAWAY_DURATION_POSITIVE = "時長必須大於 0。"
GIVEAWAY_STATUS_ACTIVE = "進行中"
GIVEAWAY_STATUS_ENDED = "已結束"
GIVEAWAY_FREE = "免費"
GIVEAWAY_PRICE = "每張 {price}"
GIVEAWAY_DESCRIPTION = (
    "編號：`{id}`\n得獎名額：**{winner_count}**\n"
    "參加方式：**{price}**｜每人上限：**{limit}**\n結束：{ending}"
)
GIVEAWAY_PAID_HEADER = "# 進行中付費抽獎"
GIVEAWAY_PAID_EMPTY = "目前沒有進行中的付費抽獎。"
GIVEAWAY_LINK = " [前往活動]({link})"
GIVEAWAY_REROLL_RESULT = "🔁 抽獎 `#{id}` 重抽結果：{winners}"
GIVEAWAY_NO_REROLL_CANDIDATE = "無可重抽人選"
ERR_NO_REROLL_CANDIDATE = "已經沒有可以重抽的人選了。"
ERR_REROLL_LIMIT = "同一場抽獎最多只能重抽 {limit} 次。"
ERR_REROLL_COOLDOWN = "重抽冷卻中，請於 {minutes} 分鐘後再試。"
GIVEAWAY_CREATED = "抽獎已建立，編號 `{giveaway_id}`。"
GIVEAWAY_ENTERED = "參加成功！目前權重：**{weight}**。"
GIVEAWAY_ENDED_NONE = "🎁 抽獎「{prize}」已結束，但沒有人參加。"
GIVEAWAY_ENDED = "🎉 抽獎「{prize}」得獎者：{winners}"

POLL_TITLE = "# 📊 原生投票"
POLL_CREATE = "建立投票"
POLL_LIST = "查看進行中投票"
POLL_CREATED = "原生投票已建立。"
POLL_FORBIDDEN = "你沒有建立投票的身分組。"
POLL_ENDED = "📊 投票「{question}」已結束，結果已保存。"
POLL_QUESTION = "投票題目"
POLL_OPTIONS = "選項（每行一個，2–10 個）"
POLL_DURATION_HOURS = "時長（小時，1–768）"
POLL_MULTIPLE = "允許複選？（是／否）"
POLL_MULTIPLE_INVALID = "複選欄位請輸入「是」或「否」。"
POLL_MULTIPLE_DEFAULT = "否"
POLL_ACTIVE_HEADER = "# 進行中投票"
POLL_ACTIVE_EMPTY = "目前沒有進行中的投票。"
POLL_LINK = " [前往投票]({link})"

BLACKJACK_TITLE = "# 🃏 美式六副牌 21 點"
BLACKJACK_RULES = "H17・Blackjack 3:2・保險 2:1・Late Surrender・DAS・最多四手"
BLACKJACK_CUSTOM_BET = "自訂下注"
BLACKJACK_STATS = "我的戰績"
BLACKJACK_NO_GAME = "找不到進行中的牌局。"
BLACKJACK_EVEN_BET = "為精確結算 3:2 與半注，21 點下注必須是偶數。"
BLACKJACK_REFUNDED = "原牌局訊息不存在，已退回 **{amount}**。"
BLACKJACK_HIT = "要牌"
BLACKJACK_STAND = "停牌"
BLACKJACK_DOUBLE = "加倍"
BLACKJACK_SPLIT = "分牌"
BLACKJACK_SURRENDER = "投降"
BLACKJACK_INSURANCE = "買保險"
BLACKJACK_NO_INSURANCE = "不要保險"
BLACKJACK_BET_AMOUNT = "下注金額"
BLACKJACK_DEALER_LINE = "**莊家：** {cards}"
BLACKJACK_HAND_LINE = "{marker}**第 {number} 手：** {cards}（{value}）｜下注 {bet}{result}"
BLACKJACK_INSURANCE_OFFER = "莊家明牌為 A：可購買原注一半的保險。"
BLACKJACK_REFUND_LINE = "已退款：**{amount}**"
BLACKJACK_SETTLEMENT_LINE = "\n總下注：**{staked}**｜返還：**{credit}**｜淨額：**{net:+}**"
BLACKJACK_EMBED_TITLE = "🃏 HoRo 21 點"
BLACKJACK_FOOTER = "玩家 {user_id}｜牌局 {game_id}"
BLACKJACK_QUICK_BET = "下注 {amount}"
BLACKJACK_NO_STATS = "尚未有牌局戰績。"
BLACKJACK_STATS_TEXT = (
    "# 🃏 我的戰績\n勝／敗／和：**{wins}／{losses}／{pushes}**\n"
    "Blackjack：**{blackjacks}**\n總下注：**{wagered}**｜總返還：**{won}**"
)
BLACKJACK_GAME_CREATED = "牌局已建立：[前往牌桌]({link})"
BLACKJACK_RESULT_WIN = "勝"
BLACKJACK_RESULT_LOSS = "敗"
BLACKJACK_RESULT_PUSH = "和"
BLACKJACK_RESULT_NATURAL = "Blackjack"
BLACKJACK_RESULT_SURRENDER = "投降"

# AI 聊天與日誌事件文字
AI_DISABLED = "此伺服器尚未完整設定 AI 聊天。"
AI_FORBIDDEN = "你不在 AI 允許的頻道或身分組內。"
AI_QUOTA = "今天的 AI 使用配額已用完。"
AI_RATE_LIMIT = "請稍候幾秒再詢問。"
AI_UPSTREAM_ERROR = "AI 服務暫時無法回應，請稍後再試。"
AI_MODEL_SAVED = "AI 模型已切換為 `{model}`。"
AI_SYSTEM_PROMPT = (
    "你是此 Discord 伺服器內的助理。請使用繁體中文，回答清楚、簡潔，且不要聲稱看過未提供的資料。"
)
AI_EMPTY_PROMPT = "請問有什麼需要協助？"
AI_RESPONSE_TRUNCATED = "\n\n（回應過長，已截斷）"
REDACTED = "[已遮罩]"

EVENT_MEMBER_JOINED = "📥 {member} 加入伺服器。"
EVENT_MEMBER_LEFT = "📤 {member} 離開伺服器。"
EVENT_MESSAGE_DELETED = "🗑️ {author} 在 {channel} 的訊息遭刪除：\n{content}"
EVENT_MESSAGE_EDITED = "✏️ {author} 在 {channel} 編輯訊息：\n**原文：** {before}\n**新文：** {after}"
EVENT_CONTENT_UNCACHED = "（內容不在快取中）"
EVENT_NO_TEXT = "（無文字）"

# 設定總覽頁的四行摘要：一行一模組，前面由 ui.status.badge() 補狀態徽章。
# 清單一律只寫數量、不展開 mention：25 個頻道加 25 個身分組的 mention 約 1000 字元，
# 四行就足以吃掉容器的字元上限；而且四行長度相近才對得齊，一眼掃得出哪個模組沒設。
SETTING_NOT_CONFIGURED = "未設定"
SETTINGS_EDIT = "編輯"
SETTINGS_LOG_LINE = "**{title}**：{channel}・成員 {members}・訊息 {messages}"
SETTINGS_ECONOMY_LINE = "**{title}**：{currency}・簽到 **{daily}**・下注 **{minimum}–{maximum}**"
SETTINGS_POLL_LINE = "**{title}**：身分組 {roles}"
SETTINGS_AI_LINE = "**{title}**：模型 **{model}**・頻道 {channels}・身分組 {roles}"
TOGGLE_ON = "開"
TOGGLE_OFF = "關"

# 服務層驗證訊息（會由互動錯誤處理器顯示）
ERR_UNKNOWN_SETTINGS = "未知設定欄位：{fields}"
ERR_CURRENCY_LENGTH = "貨幣名稱須為 1–50 字"
ERR_AMOUNT_NEGATIVE = "金額不可為負數"
ERR_AI_QUOTA_POSITIVE = "AI 配額必須大於 0"
ERR_AI_MODEL_LENGTH = "AI 模型名稱須為 1–200 字"
ERR_BET_LIMITS = "21 點上限必須大於或等於正數下限"
ERR_IDEMPOTENCY_KEY = "冪等鍵長度不正確"
ERR_INSUFFICIENT_FUNDS = "餘額不足"
ERR_DAILY_POSITIVE = "簽到金額必須大於 0"
ERR_SELF_TRANSFER = "不能轉帳給自己"
ERR_TRANSFER_POSITIVE = "轉帳金額必須大於 0"
ERR_TRANSFER_LIMIT = "單筆轉帳不可超過 {limit:,}"
ERR_BALANCE_LIMIT = "餘額上限為 {limit:,}，這筆交易會超過上限"
ERR_ADJUST_NONZERO = "調整金額不可為 0"
ERR_LEADERBOARD_LIMIT = "排行榜筆數須介於 1–100"
ERR_PRIZE_LENGTH = "獎品須為 1–300 字"
ERR_WINNER_COUNT = "得獎名額須介於 1–20"
ERR_END_FUTURE = "結束時間必須在未來"
ERR_TICKET_PRICE = "抽獎券價格不可為負數"
ERR_ENTRY_LIMIT = "每人上限須介於 1–10,000"
ERR_GIVEAWAY_NOT_FOUND = "找不到抽獎"
ERR_QUANTITY_POSITIVE = "數量必須大於 0"
ERR_GIVEAWAY_ENDED = "抽獎已結束"
ERR_ENTRY_LIMIT_EXCEEDED = "購買後會超過每人上限"
ERR_GIVEAWAY_STATE = "抽獎狀態不可結算"
ERR_COMPLETED_GIVEAWAY_NOT_FOUND = "找不到已完成的抽獎"
ERR_POLL_QUESTION = "投票題目須為 1–300 字"
ERR_POLL_ANSWER_COUNT = "投票選項須為 2–10 個"
ERR_POLL_ANSWER_LENGTH = "每個投票選項不可超過 55 字"
ERR_POLL_DUPLICATE = "投票選項不可重複"
ERR_POLL_DURATION = "投票時長須介於 1 小時與 32 天"
ERR_POLL_NOT_FOUND = "找不到投票"
ERR_POLL_STATE = "投票狀態不可結算"
ERR_DECKS_POSITIVE = "牌副數必須大於 0"
ERR_SHOE_EMPTY = "牌靴已空"
ERR_BET_POSITIVE = "下注必須大於 0"
ERR_SHOE_TOO_SMALL = "牌靴至少需要四張牌"
ERR_INSURANCE_PHASE = "目前不能選擇保險"
ERR_INSURANCE_AMOUNT = "保險金額必須為原注的一半"
ERR_PLAYER_PHASE = "目前不是玩家操作階段"
ERR_CURRENT_HAND = "找不到目前手牌"
ERR_HAND_FINISHED = "這手牌已完成"
ERR_DOUBLE = "目前不能加倍"
ERR_SPLIT = "目前不能分牌"
ERR_SURRENDER = "目前不能投降"
ERR_DEALER_PHASE = "目前不是莊家階段"
ERR_SETTLEMENT_PHASE = "牌局尚未進入結算階段"
ERR_GAME_NOT_FOUND = "找不到牌局"
ERR_ACTIVE_GAME = "已有進行中的牌局"
ERR_BET_RANGE = "下注須介於 {minimum} 與 {maximum} 之間"
ERR_BET_ALREADY_HANDLED = "這次下注已處理"
ERR_GAME_ACTION_PHASE = "目前不能執行牌局動作"
ERR_GAME_ACTION = "目前不能執行這個動作"
ERR_UNKNOWN_GAME_ACTION = "未知的牌局動作"
